"""The end-to-end campaign generation pipeline: intake -> writers' room ->
per-episode storyboard -> continuity check -> video routing -> assembly.

Extracted from ``routers/campaigns.py`` so it can be invoked from a real
Celery task (see ``worker.py``) instead of only ever running in-process via
FastAPI's ``BackgroundTasks``. Running it via ``BackgroundTasks`` meant the
whole pipeline lived and died with the API server process — a crash or
restart mid-pipeline silently dropped in-flight campaigns, and everything
ran on the API pod instead of the dedicated worker fleet that the Helm chart
(`infra/helm/showrunner/templates/worker-deployment.yaml`) already
provisions for exactly this purpose.
"""

from __future__ import annotations

import logging
import uuid

from showrunner_api.agents.creative.brand_brief_intake import BrandBriefIntakeAgent
from showrunner_api.agents.creative.writers_room import WritersRoomAgent
from showrunner_api.agents.production.assembly import AssemblyAgent
from showrunner_api.agents.production.storyboard import StoryboardAgent
from showrunner_api.agents.quality.continuity_gate import ContinuityGateAgent
from showrunner_api.agents.video.routing import VideoRoutingAgent
from showrunner_api.infra.db import SessionLocal

logger = logging.getLogger(__name__)


async def run_campaign_pipeline(project_id: uuid.UUID, workspace_id: uuid.UUID, raw_brief: str) -> None:
    """Background pipeline that orchestrates the entire agentic flow."""
    logger.info("Starting pipeline for project %s", project_id)
    async with SessionLocal() as db:
        try:
            # 1. Intake
            intake_agent = BrandBriefIntakeAgent(db=db)
            intake_result = await intake_agent.execute(
                project_id=project_id,
                workspace_id=workspace_id,
                input_json={"raw_brief": raw_brief},
            )

            # 2. Writers Room (Generates Story Arc and Episodes)
            writers_room = WritersRoomAgent(db=db)
            writers_result = await writers_room.execute(
                project_id=project_id,
                workspace_id=workspace_id,
                input_json={"structured_brief": intake_result},
            )

            # For each episode generated by writers room, run the rest of the pipeline
            episodes = writers_result.get("episodes", [])
            for ep_data in episodes:
                ep_id_str = ep_data.get("episode_id")
                if not ep_id_str:
                    continue

                # 3. Storyboard
                storyboard_agent = StoryboardAgent(db=db)
                sb_result = await storyboard_agent.execute(
                    project_id=project_id,
                    workspace_id=workspace_id,
                    episode_id=uuid.UUID(ep_id_str),
                    input_json={"episode_synopsis": ep_data.get("synopsis", "")},
                )

                # 4. Continuity Gate (Text-based script validation)
                continuity_agent = ContinuityGateAgent(db=db)
                cont_result = await continuity_agent.execute(
                    project_id=project_id,
                    workspace_id=workspace_id,
                    episode_id=uuid.UUID(ep_id_str),
                    input_json={"episodes": [sb_result]},
                )

                if not cont_result.get("passed"):
                    logger.warning("Continuity failed for ep %s: %s", ep_id_str, cont_result)
                    # In a real app we'd trigger a rewrite loop. We proceed with a warning for now.

                # 5. Video Routing & Rendering
                routing_agent = VideoRoutingAgent(db=db)
                routing_result = await routing_agent.execute(
                    project_id=project_id,
                    workspace_id=workspace_id,
                    episode_id=uuid.UUID(ep_id_str),
                    input_json={
                        "shots": sb_result.get("shots", []),
                        "reference_clip_path": None,  # Assuming no reference passed yet
                    },
                )

                # 6. Assembly
                assembly_agent = AssemblyAgent(db=db)
                await assembly_agent.execute(
                    project_id=project_id,
                    workspace_id=workspace_id,
                    episode_id=uuid.UUID(ep_id_str),
                    input_json={
                        "clips": routing_result.get("clips", []),
                        "job_dir": routing_result.get("job_dir"),
                    },
                )
        except Exception:
            logger.exception("Pipeline failed for project %s", project_id)
            raise
