"""The end-to-end campaign generation pipeline: intake -> writers' room ->
per-episode storyboard -> continuity check -> video routing -> assembly.

Extracted from ``routers/campaigns.py`` so it can be invoked from a real
Celery task (see ``worker.py``) instead of only ever running in-process via
FastAPI's ``BackgroundTasks``. Running it via ``BackgroundTasks`` meant the
whole pipeline lived and died with the API server process — a crash or
restart mid-pipeline silently dropped in-flight campaigns, and everything
ran on the API pod instead of the dedicated worker fleet that the Helm chart
(`infra/helm/showrunner/templates/worker-deployment.yaml`) already
provisions for exactly this purpose.
"""

from __future__ import annotations

import asyncio
import logging
import uuid

from sqlalchemy import select

from showrunner_api.agents.creative.brand_brief_intake import BrandBriefIntakeAgent
from showrunner_api.agents.creative.writers_room import WritersRoomAgent
from showrunner_api.agents.production.assembly import AssemblyAgent
from showrunner_api.agents.production.storyboard import StoryboardAgent
from showrunner_api.agents.quality.continuity_gate import ContinuityGateAgent
from showrunner_api.agents.video.routing import VideoRoutingAgent
from showrunner_api.infra.db import SessionLocal
from showrunner_api.models.core import Project
from showrunner_api.services.series_bible import SeriesBibleService

logger = logging.getLogger(__name__)

# Timeout configuration (seconds)
AGENT_TIMEOUT = 60.0  # Each *text* agent call (intake/writers room/storyboard/continuity) times out after 60 seconds
# FIXED: VideoRoutingAgent doesn't just call an LLM — it submits a real Wan
# render job to Dashscope and polls it (see llm_client._poll_task), which
# generate_video_t2v() itself budgets up to 600s for, times up to 3 retry
# attempts per shot (see routing.py's _render_with_retry). The old code wrapped
# this step in the same AGENT_TIMEOUT=60s used for fast LLM calls, so
# asyncio.wait_for() killed it long before Dashscope could ever report
# "succeeded" — visible in the logs as the pipeline going quiet mid-"RUNNING".
VIDEO_AGENT_TIMEOUT = 900.0  # Step 5 (Video Routing) gets its own, much larger ceiling
PIPELINE_TIMEOUT = 3600.0  # Entire pipeline times out after 1 hour, sized to fit several
# episodes each spending up to VIDEO_AGENT_TIMEOUT in Step 5. If episode counts grow
# beyond ~3, consider making this scale with len(episodes) instead of a flat constant.


async def run_campaign_pipeline(project_id: uuid.UUID, workspace_id: uuid.UUID, raw_brief: str) -> None:
    """Background pipeline that orchestrates the entire agentic flow."""
    logger.info("Starting pipeline for project %s", project_id)

    try:
        async with asyncio.timeout(PIPELINE_TIMEOUT):
            async with SessionLocal() as db:
                try:
                    # 1. Intake
                    logger.info("📝 Step 1/6: Running Brand Brief Intake...")
                    intake_agent = BrandBriefIntakeAgent(db=db)
                    intake_result = await asyncio.wait_for(
                        intake_agent.execute(
                            project_id=project_id,
                            workspace_id=workspace_id,
                            input_json={"raw_brief": raw_brief},
                        ),
                        timeout=AGENT_TIMEOUT
                    )
                    logger.info("✓ Intake completed")

                    # 2. Writers Room (Generates Story Arc and Episodes)
                    logger.info("✍️ Step 2/6: Running Writers Room...")
                    writers_room = WritersRoomAgent(db=db)
                    writers_result = await asyncio.wait_for(
                        writers_room.execute(
                            project_id=project_id,
                            workspace_id=workspace_id,
                            input_json={"structured_brief": intake_result},
                        ),
                        timeout=AGENT_TIMEOUT
                    )
                    logger.info("✓ Writers Room completed")

                    # Brand logo is static for the whole project — resolve once. Locked
                    # characters, by contrast, are refetched at the top of each episode
                    # loop below: a character auto-bootstrapped while rendering episode 1
                    # (see routing.py) needs to be visible to episode 2's storyboard and
                    # routing steps, not just to episodes started after this line ran.
                    series_bible = SeriesBibleService(db=db)

                    project_row = (
                        await db.execute(select(Project).where(Project.id == project_id))
                    ).scalars().first()
                    logo_path = project_row.brand_logo_path if project_row else None

                    # For each episode generated by writers room, run the rest of the pipeline
                    episodes = writers_result.get("episodes", [])
                    logger.info(f"🎬 Processing {len(episodes)} episode(s)...")

                    for idx, ep_data in enumerate(episodes, 1):
                        ep_id_str = ep_data.get("episode_id")
                        if not ep_id_str:
                            logger.warning("Skipping episode without ID")
                            continue

                        logger.info(f"▶️ Episode {idx}/{len(episodes)}: {ep_id_str[:8]}...")

                        # 3. Storyboard
                        # FIXED: StoryboardAgent.run() reads input_json["synopsis"]
                        # (see agents/production/storyboard.py:
                        #   episode_synopsis = input_json.get("synopsis", "")
                        #   if not episode_synopsis: return {"error": "synopsis is required"}
                        # ) but this call was sending the value under the key
                        # "episode_synopsis" instead. That mismatch meant every
                        # single episode, on every run, immediately hit the
                        # "synopsis is required" guard and returned an error dict
                        # with zero shots. Nothing downstream checked for that
                        # error, so the pipeline logged "✓ Storyboard completed"
                        # and kept going anyway — continuity got an empty shot
                        # list, routing rendered zero clips, and assembly's own
                        # "clips are required" guard silently failed too, all
                        # while every step logged as successful. Videos never
                        # rendered even though the pipeline reported full success.
                        logger.info(f"   📋 Step 3/6: Storyboarding...")
                        # Refetched per-episode (not hoisted above the loop) so a
                        # character auto-bootstrapped during a previous episode's
                        # Step 5 is already known here.
                        locked_character_refs = await series_bible.get_locked_reference_images(project_id)
                        storyboard_agent = StoryboardAgent(db=db)
                        sb_result = await asyncio.wait_for(
                            storyboard_agent.execute(
                                project_id=project_id,
                                workspace_id=workspace_id,
                                episode_id=uuid.UUID(ep_id_str),
                                input_json={
                                    "synopsis": ep_data.get("synopsis", ""),
                                    "locked_characters": list(locked_character_refs.keys()),
                                },
                            ),
                            timeout=AGENT_TIMEOUT
                        )
                        if "error" in sb_result:
                            logger.error(
                                "   ✗ Storyboard failed for episode %s: %s",
                                ep_id_str, sb_result["error"],
                            )
                            continue  # nothing to build on for this episode — skip it
                        logger.info(f"   ✓ Storyboard completed")

                        # 4. Continuity Gate (Text-based script validation)
                        # sb_result is StoryboardAgent's output (a list of shots:
                        # shot_number, camera_angle, action, dialogue,
                        # estimated_duration_sec) and never contains a `synopsis`
                        # field on its own. Merge the real episode data (title,
                        # synopsis, episode_number — from ep_data, the Writers Room
                        # output) together with the shot breakdown so the checker
                        # has something real to validate instead of always flagging
                        # a missing synopsis.
                        episode_for_continuity = {
                            **ep_data,
                            "shots": sb_result.get("shots", []),
                        }
                        logger.info(f"   🔍 Step 4/6: Continuity Check...")
                        continuity_agent = ContinuityGateAgent(db=db)
                        cont_result = await asyncio.wait_for(
                            continuity_agent.execute(
                                project_id=project_id,
                                workspace_id=workspace_id,
                                episode_id=uuid.UUID(ep_id_str),
                                input_json={"episodes": [episode_for_continuity]},
                            ),
                            timeout=AGENT_TIMEOUT
                        )

                        if not cont_result.get("passed"):
                            logger.warning("⚠️ Continuity failed for ep %s: %s", ep_id_str, cont_result)
                            # In a real app we'd trigger a rewrite loop. We proceed with a warning for now.
                        else:
                            logger.info(f"   ✓ Continuity passed")

                        # 5. Video Routing & Rendering
                        logger.info(f"   🎥 Step 5/6: Video Routing...")
                        routing_agent = VideoRoutingAgent(db=db)
                        routing_result = await asyncio.wait_for(
                            routing_agent.execute(
                                project_id=project_id,
                                workspace_id=workspace_id,
                                episode_id=uuid.UUID(ep_id_str),
                                input_json={
                                    "shots": sb_result.get("shots", []),
                                    # FIXED: this used to be hardcoded to None, which made
                                    # VisualCriticAgent.evaluate_clip() auto-pass every shot
                                    # with score=1.0 and meant no shot was ever conditioned
                                    # on a reference image — the actual root cause of
                                    # character drift. Now passes the real locked-character
                                    # map (name -> reference still), which routing.py uses
                                    # both to select i2v conditioning and to hand the
                                    # Visual Critic something real to check identity against.
                                    "character_refs": locked_character_refs,
                                },
                            ),
                            timeout=VIDEO_AGENT_TIMEOUT
                        )
                        if "error" in routing_result or not routing_result.get("clips"):
                            logger.error(
                                "   ✗ Video Routing produced no clips for episode %s: %s",
                                ep_id_str, routing_result,
                            )
                            continue
                        logger.info(f"   ✓ Video Routing completed")

                        # 6. Assembly
                        logger.info(f"   🎬 Step 6/6: Assembly...")
                        assembly_agent = AssemblyAgent(db=db)
                        assembly_result = await asyncio.wait_for(
                            assembly_agent.execute(
                                project_id=project_id,
                                workspace_id=workspace_id,
                                episode_id=uuid.UUID(ep_id_str),
                                input_json={
                                    # FIXED: BaseAgent.execute()'s episode_id= kwarg only
                                    # populates the AgentJob audit row (see base.py's
                                    # `enriched_input` — it merges in _project_id and
                                    # _workspace_id but never episode_id). AssemblyAgent.run()
                                    # itself reads input_json["episode_id"] to build the output
                                    # filename and look up the Episode row, so it must be passed
                                    # explicitly here too, not just as the execute() kwarg.
                                    "episode_id": ep_id_str,
                                    "clips": routing_result.get("clips", []),
                                    "job_dir": routing_result.get("job_dir"),
                                    "logo_path": logo_path,
                                },
                            ),
                            timeout=AGENT_TIMEOUT
                        )
                        if "error" in assembly_result:
                            logger.error(
                                "   ✗ Assembly failed for episode %s: %s",
                                ep_id_str, assembly_result["error"],
                            )
                            continue
                        logger.info(f"   ✓ Assembly completed")
                        logger.info(f"✅ Episode {idx}/{len(episodes)} COMPLETE")

                    logger.info("🎉 Pipeline completed successfully for project %s", project_id)

                except asyncio.TimeoutError as e:
                    # NOTE: this fires for ANY step's asyncio.wait_for() — could be a 60s
                    # text-agent step or the 900s Video Routing step. Don't hardcode
                    # AGENT_TIMEOUT here or a Step 5 timeout misreports itself as "60s".
                    logger.error(f"⏱️ Agent execution timed out: {e}")
                    raise
                except Exception as e:
                    logger.exception(f"❌ Pipeline step failed for project %s: {e}", project_id)
                    raise

    except asyncio.TimeoutError:
        logger.error(f"⏱️ Entire pipeline timed out after {PIPELINE_TIMEOUT}s for project %s", project_id)
        raise
    except Exception:
        logger.exception(f"❌ Pipeline failed for project %s", project_id)
        raise
