"""The end-to-end campaign generation pipeline: intake -> writers' room ->
per-episode storyboard -> continuity check -> video routing -> assembly.

Extracted from ``routers/campaigns.py`` so it can be invoked from a real
Celery task (see ``worker.py``) instead of only ever running in-process via
FastAPI's ``BackgroundTasks``. Running it via ``BackgroundTasks`` meant the
whole pipeline lived and died with the API server process — a crash or
restart mid-pipeline silently dropped in-flight campaigns, and everything
ran on the API pod instead of the dedicated worker fleet that the Helm chart
(`infra/helm/showrunner/templates/worker-deployment.yaml`) already
provisions for exactly this purpose.
"""

from __future__ import annotations

import asyncio
import logging
import uuid

from showrunner_api.agents.creative.brand_brief_intake import BrandBriefIntakeAgent
from showrunner_api.agents.creative.writers_room import WritersRoomAgent
from showrunner_api.agents.production.assembly import AssemblyAgent
from showrunner_api.agents.production.storyboard import StoryboardAgent
from showrunner_api.agents.quality.continuity_gate import ContinuityGateAgent
from showrunner_api.agents.video.routing import VideoRoutingAgent
from showrunner_api.infra.db import SessionLocal

logger = logging.getLogger(__name__)

# Timeout configuration (seconds)
AGENT_TIMEOUT = 60.0  # Each agent call times out after 60 seconds
PIPELINE_TIMEOUT = 600.0  # Entire pipeline times out after 10 minutes


async def run_campaign_pipeline(project_id: uuid.UUID, workspace_id: uuid.UUID, raw_brief: str) -> None:
    """Background pipeline that orchestrates the entire agentic flow."""
    logger.info("Starting pipeline for project %s", project_id)

    try:
        async with asyncio.timeout(PIPELINE_TIMEOUT):
            async with SessionLocal() as db:
                try:
                    # 1. Intake
                    logger.info("📝 Step 1/6: Running Brand Brief Intake...")
                    intake_agent = BrandBriefIntakeAgent(db=db)
                    intake_result = await asyncio.wait_for(
                        intake_agent.execute(
                            project_id=project_id,
                            workspace_id=workspace_id,
                            input_json={"raw_brief": raw_brief},
                        ),
                        timeout=AGENT_TIMEOUT
                    )
                    logger.info("✓ Intake completed")

                    # 2. Writers Room (Generates Story Arc and Episodes)
                    logger.info("✍️ Step 2/6: Running Writers Room...")
                    writers_room = WritersRoomAgent(db=db)
                    writers_result = await asyncio.wait_for(
                        writers_room.execute(
                            project_id=project_id,
                            workspace_id=workspace_id,
                            input_json={"structured_brief": intake_result},
                        ),
                        timeout=AGENT_TIMEOUT
                    )
                    logger.info("✓ Writers Room completed")

                    # For each episode generated by writers room, run the rest of the pipeline
                    episodes = writers_result.get("episodes", [])
                    logger.info(f"🎬 Processing {len(episodes)} episode(s)...")

                    for idx, ep_data in enumerate(episodes, 1):
                        ep_id_str = ep_data.get("episode_id")
                        if not ep_id_str:
                            logger.warning("Skipping episode without ID")
                            continue

                        logger.info(f"▶️ Episode {idx}/{len(episodes)}: {ep_id_str[:8]}...")

                        # 3. Storyboard
                        # FIXED: StoryboardAgent.run() reads input_json["synopsis"]
                        # (see agents/production/storyboard.py:
                        #   episode_synopsis = input_json.get("synopsis", "")
                        #   if not episode_synopsis: return {"error": "synopsis is required"}
                        # ) but this call was sending the value under the key
                        # "episode_synopsis" instead. That mismatch meant every
                        # single episode, on every run, immediately hit the
                        # "synopsis is required" guard and returned an error dict
                        # with zero shots. Nothing downstream checked for that
                        # error, so the pipeline logged "✓ Storyboard completed"
                        # and kept going anyway — continuity got an empty shot
                        # list, routing rendered zero clips, and assembly's own
                        # "clips are required" guard silently failed too, all
                        # while every step logged as successful. Videos never
                        # rendered even though the pipeline reported full success.
                        logger.info(f"   📋 Step 3/6: Storyboarding...")
                        storyboard_agent = StoryboardAgent(db=db)
                        sb_result = await asyncio.wait_for(
                            storyboard_agent.execute(
                                project_id=project_id,
                                workspace_id=workspace_id,
                                episode_id=uuid.UUID(ep_id_str),
                                input_json={"synopsis": ep_data.get("synopsis", "")},
                            ),
                            timeout=AGENT_TIMEOUT
                        )
                        if "error" in sb_result:
                            logger.error(
                                "   ✗ Storyboard failed for episode %s: %s",
                                ep_id_str, sb_result["error"],
                            )
                            continue  # nothing to build on for this episode — skip it
                        logger.info(f"   ✓ Storyboard completed")

                        # 4. Continuity Gate (Text-based script validation)
                        # sb_result is StoryboardAgent's output (a list of shots:
                        # shot_number, camera_angle, action, dialogue,
                        # estimated_duration_sec) and never contains a `synopsis`
                        # field on its own. Merge the real episode data (title,
                        # synopsis, episode_number — from ep_data, the Writers Room
                        # output) together with the shot breakdown so the checker
                        # has something real to validate instead of always flagging
                        # a missing synopsis.
                        episode_for_continuity = {
                            **ep_data,
                            "shots": sb_result.get("shots", []),
                        }
                        logger.info(f"   🔍 Step 4/6: Continuity Check...")
                        continuity_agent = ContinuityGateAgent(db=db)
                        cont_result = await asyncio.wait_for(
                            continuity_agent.execute(
                                project_id=project_id,
                                workspace_id=workspace_id,
                                episode_id=uuid.UUID(ep_id_str),
                                input_json={"episodes": [episode_for_continuity]},
                            ),
                            timeout=AGENT_TIMEOUT
                        )

                        if not cont_result.get("passed"):
                            logger.warning("⚠️ Continuity failed for ep %s: %s", ep_id_str, cont_result)
                            # In a real app we'd trigger a rewrite loop. We proceed with a warning for now.
                        else:
                            logger.info(f"   ✓ Continuity passed")

                        # 5. Video Routing & Rendering
                        logger.info(f"   🎥 Step 5/6: Video Routing...")
                        routing_agent = VideoRoutingAgent(db=db)
                        routing_result = await asyncio.wait_for(
                            routing_agent.execute(
                                project_id=project_id,
                                workspace_id=workspace_id,
                                episode_id=uuid.UUID(ep_id_str),
                                input_json={
                                    "shots": sb_result.get("shots", []),
                                    "reference_clip_path": None,  # Assuming no reference passed yet
                                },
                            ),
                            timeout=AGENT_TIMEOUT
                        )
                        if "error" in routing_result or not routing_result.get("clips"):
                            logger.error(
                                "   ✗ Video Routing produced no clips for episode %s: %s",
                                ep_id_str, routing_result,
                            )
                            continue
                        logger.info(f"   ✓ Video Routing completed")

                        # 6. Assembly
                        logger.info(f"   🎬 Step 6/6: Assembly...")
                        assembly_agent = AssemblyAgent(db=db)
                        assembly_result = await asyncio.wait_for(
                            assembly_agent.execute(
                                project_id=project_id,
                                workspace_id=workspace_id,
                                episode_id=uuid.UUID(ep_id_str),
                                input_json={
                                    "clips": routing_result.get("clips", []),
                                    "job_dir": routing_result.get("job_dir"),
                                },
                            ),
                            timeout=AGENT_TIMEOUT
                        )
                        if "error" in assembly_result:
                            logger.error(
                                "   ✗ Assembly failed for episode %s: %s",
                                ep_id_str, assembly_result["error"],
                            )
                            continue
                        logger.info(f"   ✓ Assembly completed")
                        logger.info(f"✅ Episode {idx}/{len(episodes)} COMPLETE")

                    logger.info("🎉 Pipeline completed successfully for project %s", project_id)

                except asyncio.TimeoutError as e:
                    logger.error(f"⏱️ Agent execution timed out after {AGENT_TIMEOUT}s: {e}")
                    raise
                except Exception as e:
                    logger.exception(f"❌ Pipeline step failed for project %s: {e}", project_id)
                    raise

    except asyncio.TimeoutError:
        logger.error(f"⏱️ Entire pipeline timed out after {PIPELINE_TIMEOUT}s for project %s", project_id)
        raise
    except Exception:
        logger.exception(f"❌ Pipeline failed for project %s", project_id)
        raise
